### ISSUE TITLE
Implement clearing endpoints

### ISSUE THREAD

**Issue by deveaud-m** [fossology/fossology-python#114]
This is a non exhaustive list of new Fossology endpoints to be integrated to support automated license clearing:

* [x] https://github.com/fossology/fossology/pull/2477
* [x] https://github.com/fossology/fossology/pull/2480
* [x] https://github.com/fossology/fossology/pull/2481
* [x] https://github.com/fossology/fossology/pull/2483

/cc @goneall

**Comment by deveaud-m** [comment]
Dear @goneall,

a preview of the integration between Fossology's clearing endpoint and the python wrapper is now available in the `master` branch. Feel free to have a look at it.

Once Fossology's new version is released I'll created a new tag and minor update of the library.

**Comment by goneall** [comment]
Thanks @deveaud-m - changes look good to me.
