### ISSUE TITLE
missing super().__init__(message) in exception classes

### ISSUE THREAD

**Issue by alpianon** [fossology/fossology-python#123]
in `fossology/exceptions.py`, all exception classes miss the `super().__init__(message)` call, so in case of errors the message is not displayed, and something like `AuthenticationError: ('Authentication error', <Response [404]>)` is displayed instead.

Moreover, if the response code is an error code, `if response:" is always False, so it never displays the actual error message.

Something like this should work:

```python
class AuthenticationError(Error):
    """Authentication error"""

    def __init__(self, description, response=None):
        if response is not None:
            try:
                message = response.json().get("message")
            except JSONDecodeError:
                message = response.text
            self.message = f"{description}: {message} ({response.status_code})"
        else:
            self.message = description
        super().__init__(self.message)
```

**Comment by deveaud-m** [comment]
@alpianon thanks again for testing this library and providing this extremely valuable feedback.

I fully agree with your proposal, since it spreads all over the code I'll need a bit more time to fix it.
