### ISSUE TITLE
Fail for some OSS

### ISSUE THREAD

**Issue by leimaohui** [fossology/fossology-python#35]
The error will occur when scan huge source code(e.g. kernel) or some special OSS (e.g. https://sourceware.org/pub/bzip2/bzip2-1.0.8.tar.gz) by fossology-python, the error message is as following:
-------------------------------------------------------------------
 0258:    try:
     0259:        # Plain text
 *** 0260:        report = foss.download_report(report_id)
     0261:        with open(report_name, "w+") as report_file:
     0262:            report_file.write(report)
     0263:    except FossologyApiError as error:
     0264:        bb.error(error.message)
File: '/common/home/test/.local/lib/python3.8/site-packages/tenacity/__init__.py', lineno: 329, function: wrapped_f
     0325:        :param f: A function to wraps for retrying.
     0326:        """
     0327:        @_utils.wraps(f)
     0328:        def wrapped_f(*args, **kw):
 *** 0329:            return self.call(f, *args, **kw)
     0330:
     0331:        def retry_with(*args, **kwargs):
     0332:            return self.copy(*args, **kwargs).wraps(f)
     0333:
File: '/common/home/test/.local/lib/python3.8/site-packages/tenacity/__init__.py', lineno: 409, function: call
     0405:
     0406:        retry_state = RetryCallState(
     0407:            retry_object=self, fn=fn, args=args, kwargs=kwargs)
     0408:        while True:
 *** 0409:            do = self.iter(retry_state=retry_state)
     0410:            if isinstance(do, DoAttempt):
     0411:                try:
     0412:                    result = fn(*args, **kwargs)
     0413:                except BaseException:
File: '/common/home/test/.local/lib/python3.8/site-packages/tenacity/__init__.py', lineno: 369, function: iter
     0365:                return self.retry_error_callback(retry_state=retry_state)
     0366:            retry_exc = self.retry_error_cls(fut)
     0367:            if self.reraise:
     0368:                raise retry_exc.reraise()
 *** 0369:            six.raise_from(retry_exc, fut.exception())
     0370:
     0371:        if self.wait:
     0372:            sleep = self.wait(retry_state=retry_state)
     0373:        else:
File: '<string>', lineno: 3, function: raise_from
  File "<string>", line 3, in raise_from

-------------------------------------------------------------------

If I increase the sleep time in fossology/report.py,  things have been better.

**Comment by deveaud-m** [comment]
@leimaohui Thanks for reporting on this!

In case the report generation takes too long, the `TryAgain` exception is raised.

Maybe it would make sense to return a specific exception for this.

**Comment by leimaohui** [comment]
The problem is that fossology always return "Retry-After 10s"  for 503 no matter how huge source the OSS has. So, for kernel,  foss.download_report() always fails.

**Comment by deveaud-m** [comment]
> The problem is that fossology always return "Retry-After 10s" for 503 no matter how huge source the OSS has. So, for kernel, foss.download_report() always fails.

Is the report generation working via the UI?

And using a plain HTTP request: e.g. via cURL `curl -H "Authorization: Bearer $TOKEN https://fossology.mydomain.com/api/v1/report/?uploadId=xxx`?

**Comment by leimaohui** [comment]
Thank you, I got it.
