### ISSUE TITLE
list_uploads() broken in 0.1.2

### ISSUE THREAD

**Issue by djeverett** [fossology/fossology-python#38]
This was not present in 0.1.1, but in 0.1.2 I get 
```
Traceback (most recent call last):
  File "generate_report.py", line 19, in <module>
    upload_list = foss.list_uploads()
  File "/home/deverett/.virtualenvs/fossology/lib/python3.8/site-packages/fossology/uploads.py", line 372, in list_uploads
    f"Retrieved page {page} of uploads, {response.headers['X-TOTAL-PAGES']} pages are in total available"
  File "/home/deverett/.virtualenvs/fossology/lib/python3.8/site-packages/requests/structures.py", line 54, in __getitem__
    return self._store[key.lower()][1]
KeyError: 'x-total-pages'
```
when using `list_uploads()`

The headers do not contain an `X-TOTAL-PAGES` entry - dumping `response.headers` I get 
```
{'Date': 'Fri, 25 Sep 2020 09:57:46 GMT', 'Server': 'Apache/2.4.25 (Debian)', 'Cache-Control': 'max-age=0, private, must-revalidate', 'Content-Length': '221', 'Keep-Alive': 'timeout=5, max=96', 'Connection': 'Keep-Alive', 'Content-Type': 'application/json;charset=utf-8'}
```

I am running against the 3.9.0 fossology server (latest Docker image).

**Comment by deveaud-m** [comment]
@djeverett my mistake. I forgot that I was preparing the next minor release of this library against version 1.0.17 of the Fossology REST API. However the upstream Fossology REST API has not been merged and released yet which resulted in inconsistencies in the previous patch release.

I reverted the concerned commits and released another patch: https://pypi.org/project/fossology/0.1.3/.

**Comment by djeverett** [comment]
Thanks.  I can confirm that the fix works.
