### ISSUE TITLE
Extend usage of typehints

### ISSUE THREAD

**Issue by deveaud-m** [fossology/fossology-python#41]
And generate package stubs: https://mypy.readthedocs.io/en/stable/stubgen.html

**Comment by manan090301** [comment]
hello i am very exciteing to solve your issue. can i work on this issue.this is myfirst issue solving for open source. can i working on this issues?

**Comment by deveaud-m** [comment]
> hello i am very exciteing to solve your issue. can i work on this issue.this is myfirst issue solving for open source. can i working on this issues?

Hello @manan090301, you can surely try to propose a Pull Request to solve this issue. Are you an experiences Python developer? Do you know what type hints are?

**Comment by manan090301** [comment]
not much expreinced . but guide me little bit i will go trough and solve this.

**Comment by manan090301** [comment]
> > hello i am very exciteing to solve your issue. can i work on this issue.this is myfirst issue solving for open source. can i working on this issues?
> 
> Hello @manan090301, you can surely try to propose a Pull Request to solve this issue. Are you an experiences Python developer? Do you know what type hints are?

i don't know what type of hints are.

**Comment by manan090301** [comment]
@deveaud-m can you pls guide me.how can i do that?

**Comment by deveaud-m** [comment]
> @deveaud-m can you pls guide me.how can i do that?

If you don't know what typehints are and if you don't have much Python experience, you'll not be able to tackle this issue with a reasonable effort. And unfortunately I don't have time to coach you on those topics. This is quite an advanced Python topic not really related to this project itself.

I guess you should first start with doing some online advanced Python course.

**Comment by manan090301** [comment]
ok

**Comment by MananKansara0903** [comment]
@deveaud-m hello There i have worked and knowing about type hints.here i will breefly 

> > @deveaud-m can you pls guide me.how can i do that?
> 
> If you don't know what typehints are and if you don't have much Python experience, you'll not be able to tackle this issue with a reasonable effort. And unfortunately I don't have time to coach you on those topics. This is quite an advanced Python topic not really related to this project itself.
> 
> I guess you should first start with doing some online advanced Python course.

hello there @deveaud-m i am learning about how type hints work. here i have to use mypy module that check the given file is right type or not. 
Example:
`def checking(number:int) -> int:
   if(number % 10 == 0):
      return number` 
this checking should follow passing value as int and return value should be int . this is the main concept of type hints that not change the behviour of programing or any kind of functionality of it.

if let's i have make file name = firsttypehints.py that's have some code in it.
i have pip the mypy package then checking stubgen sourcefilename(firsttypehints).py that create stub file in out folder that will help developer to enhacement code devlopment. that's it.



Now can i work on this?

**Comment by manan090301** [comment]
hello there @deveaud-m i am learning about how type hints work. here i have to use mypy module that check the given file is right type or not.
Example:
def checking(number:int) -> int: if(number % 10 == 0): return number
this checking should follow passing value as int and return value should be int . this is the main concept of type hints that not change the behviour of programing or any kind of functionality of it.

if let's i have make file name = firsttypehints.py that's have some code in it.
i have pip the mypy package then checking stubgen sourcefilename(firsttypehints).py that create stub file in out folder that will help developer to enhacement code devlopment. that's it.

Now can i work on this?

**Comment by deveaud-m** [comment]
> hello there @deveaud-m i am learning about how type hints work. here i have to use mypy module that check the given file is right type or not. Example: def checking(number:int) -> int: if(number % 10 == 0): return number this checking should follow passing value as int and return value should be int . this is the main concept of type hints that not change the behviour of programing or any kind of functionality of it.
> 
> if let's i have make file name = firsttypehints.py that's have some code in it. i have pip the mypy package then checking stubgen sourcefilename(firsttypehints).py that create stub file in out folder that will help developer to enhacement code devlopment. that's it.
> 
> Now can i work on this?

Look at my first comment.

**Comment by MananKansara09** [comment]
can you pls provide your communication  way where i will ask you when am i stuck.

**Comment by deveaud-m** [comment]
Covered by #112
