### ISSUE TITLE
Use action to deploy GH pages automatically

### ISSUE THREAD

**Issue by deveaud-m** [fossology/fossology-python#60]
E.g.: https://github.com/marketplace/actions/deploy-to-github-pages

**Comment by GMishx** [comment]
Hi @deveaud-m , can I work on this?

**Comment by GMishx** [comment]
I created this branch on my fork and here is the job: https://github.com/GMishx/fossology-python/actions/runs/682778502
And the deployed page: https://gmishx.github.io/fossology-python/

Just a question, when the documentation generation will be preferred?
- On merge on master
- On a new release only

**Comment by deveaud-m** [comment]
> I created this branch on my fork and here is the job: https://github.com/GMishx/fossology-python/actions/runs/682778502
> And the deployed page: https://gmishx.github.io/fossology-python/
> 
> Just a question, when the documentation generation will be preferred?
> 
> * On merge on master
> * On a new release only

Let's do it on every `master` merge since there is no "official" release process or automatic tagging process.
