### ISSUE TITLE
Create fossology cli

### ISSUE THREAD

**Issue by deveaud-m** [fossology/fossology-python#72]
Using [click](https://palletsprojects.com/p/click/) with basic commands:

* upload source
* get upload summary
* start/restart scan jobs
* generate and download report

**Comment by gernot-h** [comment]
What about https://github.com/fossology/fossdriver? Could this be used as inspiration or even partly re-used?

**Comment by deveaud-m** [comment]
> What about https://github.com/fossology/fossdriver? Could this be used as inspiration or even partly re-used?

Definitely, the basic Fossology workflows are modeled in that library too, so using this project as inspiration totally makes sense.

**Comment by deveaud-m** [comment]
This has been implemented in #75 by @thsetz.
