### ISSUE TITLE
Document how to run a basic scan/report workflow in CI

### ISSUE THREAD

**Issue by deveaud-m** [fossology/fossology-python#73]
Create a sample automated scan workflow using Fossology container as a service.

Document how to use the automated workflow in a CI pipeline.

**Comment by ajaySahani7945** [comment]
Hi,
My name is Ajay sahani,  i would like to work on this.

**Comment by ajaySahani7945** [comment]
@deveaud-m Thanks, for assigning me this. 
And of,course Sir, i would like to know how do i start.

**Comment by deveaud-m** [comment]
Here would be the way I would proceed:

* create a test python project
* add `fossology-python` as dependency
* use a test file with source of an Open Source component, e.g. https://github.com/fossology/fossology-python/blob/main/tests/files/base-files_11.tar.xz
* pull the latest stable Fossology image as explained here: https://github.com/fossology/fossology#docker
* use the cli to perform following steps:
  * upload the source file to the local Fossology instance
  * start default scan jobs as documented in the docs
  * retrieve the scan report
* reproduce the same steps as a github action inside your project

Let me know, if you're having problems performing those steps

PS: call me Marion, I am a woman ;)

**Comment by ajaySahani7945** [comment]
Hi, Marion
*i cannot be able to pull image* using command  *docker run -p 8081:80
fossology/fossology *
*The output says docker permission denied (and more).*
What should i do? Please advise me with this problem.
Thank you.

**Comment by deveaud-m** [comment]
@ajaySahani7945 `docker pull fossology/fossology` should work out of the box.

Which machine are you using?

Could you share the output of the command above?

(Please make use of proper [markdown formatting when writing comments](https://docs.github.com/en/get-started/writing-on-github/getting-started-with-writing-and-formatting-on-github/basic-writing-and-formatting-syntax))

**Comment by ajaySahani7945** [comment]
![photo_2023-12-19_02-02-02](https://github.com/fossology/fossology-python/assets/145527877/89146198-3f1a-46c2-b7bc-adc42bc5ba9a)

## I am using LinuxOS ( LinuxMint)
_I have shared the photo of the output_
**Share some suggestion**

Thanks ## Marion

**Comment by deveaud-m** [comment]
The error says you're not allowed to pull the docker image. It seems your distribution installs the docker engine as root without giving normal users permissions to run containers. Have a look at the docker installation and search for potential resolutions in the distro's documentation.

Please do not post pictures in the issue tracker, copy&pasting the error message as code snippet would have been sufficient to understand the problem.

It seems you lack experience and knowledge to resolve this issue, maybe you should visit some computer science class or online course before trying to address a random issue in a random Open Source project.

**Comment by ajaySahani7945** [comment]
Ok, I'll check it out.

**Comment by deveaud-m** [comment]
No resonance on this issue until now, closing.
