### ISSUE TITLE
foss_cli: make check_get_report_format generic

### ISSUE THREAD

**Issue by thsetz** [fossology/fossology-python#82]
Currently the atrribute handling is hard coded -  should be generic:

**Comment by thsetz** [comment]
feat/cli-issues82and83 implements the solution

**Comment by deveaud-m** [comment]
> feat/cli-issues82and83 implements the solution

@thsetz you don't have to close the issues manually, simply reference the issue number in the pull request and the issue will get closed automatically once the PR is merged, see https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue

**Comment by thsetz** [comment]
OK

**Comment by deveaud-m** [comment]
Look like I should have used the `resolves` keyword... anyway this has been fixed in #86
