### ISSUE TITLE
Fix docstring test

### ISSUE THREAD

**Issue by deveaud-m** [fossology/fossology-python#87]
See https://github.com/fossology/fossology-python/runs/3533354750?check_suite_focus=true

**Comment by thsetz** [comment]
This is NOT the actual code of sample_workflow.rst ??? in feat-add-sample-workflow-documentation

Any solution using os.environ  failed on the github-ubuntu machine.


The actual code (was on my fork). (https://raw.githubusercontent.com/thsetz/fossology-python/feat-add-sample-workflow-documentation/docs-source/sample_workflow.rst) worked. 

How should we proceed ?

**Comment by deveaud-m** [comment]
Maybe you can rebase your branch on top of this project's `master` and look at the differences.

Afterwards create a Pull Request with the branch in this project to verify that the pipeline works.

**Comment by thsetz** [comment]
Looks like only the modifications in docs-source/sample_workflow.rst where missing.

I created a new branch (on fossology/fossology) and pushed the changes. The static checks have passed - the integration tests did NOT run.

**Comment by deveaud-m** [comment]
This has been fixed in #89
