### ISSUE TITLE
Retry-After time from the response of fossology server is not enough for download_report

### ISSUE THREAD

**Issue by leimaohui** [fossology/fossology-python#95]
Fossology server always responds "Retry-After 10 s" to download spdx file again no mater how huge the spdx file is. As a result, download_report is always failed. So, why not added a parameter of "wait_time" to allow users to customize the wait time  against actual conditions.

**Comment by deveaud-m** [comment]
@leimaohui thanks for reporting this issue. I just published a new version with the `wait_time` option for reports download, maybe you can give it a try and give me feedback if it still does not work for you.

See: https://fossology.github.io/fossology-python/report.html#fossology.report.Report.download_report
